name: Build and Deploy Nuxt 3 to GitHub Pages

on:
  push:
    branches:
      - main  # или основная ветка твоего репозитория

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Устанавливаем Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Устанавливаем зависимости
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Строим проект Nuxt 3
      - name: Build Nuxt
        run: npm run build
        env:
          SALES_DOUBLER_BASE_URL: ${{ secrets.SALES_DOUBLER_BASE_URL }}
          AFFILIATE_API_KEY: ${{ secrets.AFFILIATE_API_KEY }}
          E_COM_CATEGORY_ID: ${{ secrets.E_COM_CATEGORY_ID }}
          OFFER_PER_PAGE: ${{ secrets.OFFER_PER_PAGE}}

      # 5️⃣ Экспортируем статику (если используешь target: 'static')
      - name: Generate static files
        run: npm run generate
        env:
          SALES_DOUBLER_BASE_URL: ${{ secrets.SALES_DOUBLER_BASE_URL }}
          AFFILIATE_API_KEY: ${{ secrets.AFFILIATE_API_KEY }}
          E_COM_CATEGORY_ID: ${{ secrets.E_COM_CATEGORY_ID }}
          OFFER_PER_PAGE: ${{ secrets.OFFER_PER_PAGE}}

      # 6️⃣ Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public  # итоговая папка после nuxt generate
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
